# Generated by Django 2.2.9 on 2020-01-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankdetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='branch',
            field=models.CharField(max_length=74, null=True),
        ),
    ]
