# Generated by Django 2.2.9 on 2020-01-23 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankdetails', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bank',
            new_name='Banks',
        ),
    ]
