# Generated by Django 2.2.9 on 2020-01-23 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankdetails', '0003_auto_20200123_1513'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bank',
            table='Bank',
        ),
    ]
