# Generated by Django 2.2.9 on 2020-01-23 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankdetails', '0004_auto_20200123_1650'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bank',
            table='bank',
        ),
    ]
